function [M, K]=MountMatrix(Nos_Num, totaldeelementos, elementosfinais, E, ro)

M=zeros(3*Nos_Num);
K=zeros(3*Nos_Num);

rodaT = zeros(6);

for i=1:totaldeelementos
    Massa=[140 0 0 70 0 0;0 156 22*elementosfinais(i,1)...
        0 54 -13*elementosfinais(i,1);0 22*elementosfinais(i,1)...
        4*elementosfinais(i,1)^2 0 13*elementosfinais(i,1)...
        -3*elementosfinais(i,1)^2;...
        70 0 0 140 0 0;0 54 13*elementosfinais(i,1)...
        0 156 -22*elementosfinais(i,1);...
        0 -13*elementosfinais(i,1) -3*elementosfinais(i,1)^2 ...
        0 -22*elementosfinais(i,1) 4*elementosfinais(i,1)^2];
    Massa=ro*elementosfinais(i,2)*elementosfinais(i,1)/420*Massa;
    
    Rigidez=[elementosfinais(i,2)/elementosfinais(i,1) 0 0 ...
        -elementosfinais(i,2)/elementosfinais(i,1) 0 0;...
        0 12*elementosfinais(i,3)/elementosfinais(i,1)^3 ...
        6*elementosfinais(i,3)/elementosfinais(i,1)^2 ...
        0 -12*elementosfinais(i,3)/elementosfinais(i,1)^3 ...
        6*elementosfinais(i,3)/elementosfinais(i,1)^2;...
        0 6*elementosfinais(i,3)/elementosfinais(i,1)^2 ...
        4*elementosfinais(i,3)/elementosfinais(i,1) 0 ...
        -6*elementosfinais(i,3)/elementosfinais(i,1)^2 ...
        2*elementosfinais(i,3)/elementosfinais(i,1);...
        -elementosfinais(i,2)/elementosfinais(i,1) 0 0 ...
        elementosfinais(i,2)/elementosfinais(i,1) 0 0;...
        0 -12*elementosfinais(i,3)/elementosfinais(i,1)^3 ...
        -6*elementosfinais(i,3)/elementosfinais(i,1)^2 ...
        0 12*elementosfinais(i,3)/elementosfinais(i,1)^3 ...
        -6*elementosfinais(i,3)/elementosfinais(i,1)^2;...
        0 6*elementosfinais(i,3)/elementosfinais(i,1)^2 ...
        2*elementosfinais(i,3)/elementosfinais(i,1)...
        0 -6*elementosfinais(i,3)/elementosfinais(i,1)^2 ...
        4*elementosfinais(i,3)/elementosfinais(i,1)];
    Rigidez=E*Rigidez;

    rodaT=[cos(elementosfinais(i,4)) sin(elementosfinais(i,4)) 0 0 0 0;...
        -sin(elementosfinais(i,4)) cos(elementosfinais(i,4)) 0 0 0 0;...
        0 0 1 0 0 0;0 0 0 cos(elementosfinais(i,4))...
        sin(elementosfinais(i,4)) 0;0 0 0 -sin(elementosfinais(i,4))...
        cos(elementosfinais(i,4)) 0; 0 0 0 0 0 1];
    
    Massa=rodaT'*Massa*rodaT;
    Rigidez=rodaT'*Rigidez*rodaT;
    
    posicoes=[3*elementosfinais(i,5)-2:3*elementosfinais(i, 5),...
        3*elementosfinais(i,6)-2:3*elementosfinais(i,6)];
    M(posicoes,posicoes)=M(posicoes,posicoes)+Massa;
    K(posicoes,posicoes)=K(posicoes,posicoes)+Rigidez;
end

end

